#!/bin/bash
dir="dbo-get"
bin="build/dbo-get"
etc="etc/"

if [ ! -d dbo-get ]
then
    echo "Workspace is corrupt (try recloning)."
    exit 1
fi

make

mkdir -p $dir/bin/
cp $bin $dir/bin/
cp -r $etc $dir/etc

dpkg-deb --build dbo-get
